import {test} from 'node:test';
import assert from 'node:assert/strict';
import vm from 'node:vm';
import fs from 'node:fs';
function receiver(){const rows=[];const sheet={getSheetId:()=>0,getLastRow:()=>rows.length,setFrozenRows(){},getRange(row,col,height=1,width=1){const range={setValues(values){for(let i=0;i<height;i++){rows[row-1+i]??=[];for(let j=0;j<width;j++)rows[row-1+i][col-1+j]=values[i][j];}return range;},getValues(){return Array.from({length:height},(_,i)=>Array.from({length:width},(_,j)=>rows[row-1+i]?.[col-1+j]??''));},setFontWeight(){return range;},setBackground(){return range;},setNumberFormat(){return range;}};return range;}};let held=false;const ctx=vm.createContext({SpreadsheetApp:{openById(id){assert.equal(id,'1ItFnYnTx_-tleYx-Fko-82OVOpWCtOCHEcK_4CT5RNQ');return {getSheets:()=>[sheet]};},flush(){}},LockService:{getScriptLock(){return {tryLock(){held=true;return true;},hasLock:()=>held,releaseLock(){held=false;}};}},ContentService:{MimeType:{JSON:'json'},createTextOutput(text){return {text,setMimeType(){return this;}};}}});vm.runInContext(fs.readFileSync(new URL('../gas/Code.gs',import.meta.url),'utf8').replace('__UPLOAD_SECRET__','test-private-token'),ctx);return {rows,call(payload){return JSON.parse(ctx.doPost({postData:{contents:JSON.stringify(payload)}}).text);},health(){return JSON.parse(ctx.doGet().text);}};}
const payload={secret:'test-private-token',className:'驗收測試',seat:'1',name:'系統測試',learningScore:5,firstAssessment:4,bestAssessment:6,correctedAssessment:5,bestGame:null,completedPages:2,requestId:'local-test-00000000001'};
test('接收端建立欄位及成果，不回傳姓名或其他學生資料',()=>{const r=receiver();const result=r.call(payload);assert.equal(result.ok,true);assert.equal(result.row,2);assert.equal(r.rows.length,2);assert.equal(r.rows[1][2],'系統測試');assert.equal(result.name,undefined);assert.equal(r.health().service,'cell-explorer-results');});
test('同次重試不新增列，同一學生新一次上傳更新原列',()=>{const r=receiver();r.call(payload);assert.equal(r.call(payload).action,'unchanged');const updated=r.call({...payload,learningScore:12,requestId:'local-test-00000000002'});assert.equal(updated.action,'updated');assert.equal(updated.row,2);assert.equal(r.rows.length,2);assert.equal(r.rows[1][3],12);});
test('無驗證碼與非法分數不會寫入試算表',()=>{const r=receiver();assert.equal(r.call({...payload,secret:'wrong'}).ok,false);assert.equal(r.call({...payload,learningScore:99}).ok,false);assert.equal(r.call({...payload,seat:'=1+1'}).ok,false);assert.equal(r.rows.length,0);});
test('公式前綴以文字寫入，null 未作答分數保持空白',()=>{const r=receiver();assert.equal(r.call({...payload,name:'=SUM(1,2)'}).ok,true);assert.equal(r.rows[1][2],"'=SUM(1,2)");assert.equal(r.rows[1][7],'');});
test('遇到不同欄位的既有工作表不覆蓋',()=>{const r=receiver();r.rows.push(['既有內容']);const result=r.call(payload);assert.equal(result.ok,false);assert.match(result.error,/欄位不相符/);assert.equal(r.rows.length,1);});
