'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {OperationLayout,StepGuide} from './operation-layout';
import {Pick} from './exploration';
export function ConceptBlocks({texts}:{texts:string[]}){return <ul className="concept-blocks">{texts.map((text,i)=><li key={i}>{text.split(/(\*\*.*?\*\*)/g).map((part,j)=>part.startsWith('**')?<strong key={j}>{part.slice(2,-2)}</strong>:part)}</li>)}</ul>}
export function AtomOrder(){const [cards,setCards]=useState(['細胞','原子','生物','分子']);const [selected,setSelected]=useState<number|null>(null);const [checked,setChecked]=useState(false);const move=(from:number,to:number)=>{const next=[...cards];const [card]=next.splice(from,1);next.splice(to,0,card);setCards(next);setSelected(null);setChecked(false);};return <section className="card atom-order"><div className="section-label">互動字卡排序</div><h2>從小到大，組成生物</h2><p>請拖曳字卡，將組成的過程由小到大排列出來。</p><p className="small">也可先點選一張字卡，再點選要移到的位置；鍵盤可使用各卡的移動按鈕。</p><ol className="order-cards">{cards.map((card,i)=><li key={card} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=Number(e.dataTransfer.getData('text/plain'));if(Number.isInteger(from)&&from>=0&&from<4)move(from,i);}}><button draggable onDragStart={e=>e.dataTransfer.setData('text/plain',String(i))} aria-pressed={selected===i} onClick={()=>selected===null?setSelected(i):move(selected,i)}><span>{i+1}</span>{card}</button><div><Button variant="ghost" size="sm" disabled={i===0} aria-label={`${card}向前移`} onClick={()=>move(i,i-1)}>←</Button><Button variant="ghost" size="sm" disabled={i===3} aria-label={`${card}向後移`} onClick={()=>move(i,i+1)}>→</Button></div></li>)}</ol><Button onClick={()=>setChecked(true)}>檢查排序</Button><p role="status">{checked?(cards.join()===['原子','分子','細胞','生物'].join()?'✓ 正確！原子組成分子，分子組成細胞，細胞組成生物。':'再想想：先找出組成分子的基本單位，再往更大的層次排列。'):selected!==null?'請點選要移到的位置。':''}</p></section>}
export function ConcentrationCup(){const [water,setWater]=useState(40);const [dye,setDye]=useState(10);const total=water+dye;return <section className="card concentration-cup"><div className="section-label">動手調整 · 基準杯</div><h2>改變比例，看看濃淡</h2><div className="cup-stat"><strong>{total?(dye/total*100).toFixed(1):'—'}<small> %</small></strong><span>色素粒子所占比例</span></div><svg viewBox="0 0 320 230" role="img" aria-label={`杯中有 ${water} 個藍色水粒子與 ${dye} 個紅色色素粒子`}><path d="M20 10 V210 Q20 220 30 220 H290 Q300 220 300 210 V10" fill={`rgba(220,55,75,${total?0.04+dye/total*0.22:0})`} stroke="#7898ae" strokeWidth="3"/>{Array.from({length:total},(_,i)=><circle key={i} cx={34+(i*67%252)} cy={24+(i*43%181)} r="4.5" fill={i<dye?'#dc334a':'#2184d4'}/>)}</svg><p>🔴 色素：{dye}　🔵 水：{water}</p><div className="cup-controls">{([{label:'色素',value:dye,set:setDye},{label:'水',value:water,set:setWater}]).map(({label,value,set})=><div key={label}><Button variant="outline" disabled={value===0} onClick={()=>set(value-1)}>− {label}</Button><Button variant="outline" disabled={value===100} onClick={()=>set(value+1)}>＋ {label}</Button></div>)}</div><p className="small">濃度％＝色素粒子數 ÷（水粒子數＋色素粒子數）× 100%。這裡以粒子數比例比較濃淡；每種最多 100 個粒子。</p><Button variant="ghost" onClick={()=>{setWater(40);setDye(10);}}>回到基準杯</Button></section>}
const url='https://phet.colorado.edu/sims/html/membrane-transport/latest/membrane-transport_all.html?locale=zh_TW';
const tasks=[
['1 · 氧氣','點選下方 Simple Diffusion（簡單擴散，左一），在左側 Solutes 選第 1 個 O₂（氧氣），在 Outside（外側）按「>>」，觀察氧氣怎麼通過細胞膜。',['直接通過','需要通道才能通過','無法通過'],0],
['2 · 二氧化碳','按動畫框左下的橡皮擦回復原狀，選第 2 個 CO₂（二氧化碳），在 Outside（外側）按「>>」，觀察二氧化碳怎麼通過細胞膜。',['無法通過','直接通過','需要通道才能通過'],1],
['3 · 鈉離子','按橡皮擦回復原狀，選第 3 個 Na⁺（鈉離子），在 Outside（外側）按「>>」，觀察鈉離子怎麼通過細胞膜。',['直接通過','無法通過'],1],
['4 · 葡萄糖','按橡皮擦回復原狀，選第 5 個 Glucose（葡萄糖），在 Outside（外側）按「>>」，觀察葡萄糖怎麼通過細胞膜。',['無法通過','直接通過'],0],
['第一次測試結論','比較以上四種物質，選出正確結論。',['所有物質都可以直接通過細胞膜','氧氣和二氧化碳可以直接通過細胞膜，離子和葡萄糖不能直接通過細胞膜','只要外側粒子夠多，離子就能直接通過'],1],
['5 · 專屬通道','點選下方 Facilitated Diffusion（促進性擴散，左二），選第 3 個 Na⁺（鈉離子）。點選右側 Leakage Channels，拖曳一個黃色鈉離子通道和一個藍色鉀離子通道到細胞膜上，在 Outside（外側）按「>>」，觀察鈉離子怎麼通過細胞膜。',['可以穿過所有通道','只會穿過特定的通道','直接穿過沒有通道的膜'],1],
['6 · 葡萄糖需要什麼？','保留兩種通道，繼續選第 5 個 Glucose（葡萄糖），在 Outside（外側）按「>>」加入葡萄糖，觀察是否能通過膜上的通道。',['葡萄糖可以穿過所有離子通道','葡萄糖無法穿過黃色鈉離子通道和藍色鉀離子通道，需要特定的運輸蛋白'],1],
['第二次測試結論','比較鈉離子與葡萄糖的通膜需求。',['離子和葡萄糖需要各自專屬的運輸蛋白協助','任何通道都可以讓所有物質通過'],0]
] as const;
export function MembraneExploration(){const [active,setActive]=useState(0);const [answers,setAnswers]=useState<Record<number,string>>({});const [checked,setChecked]=useState<Record<number,boolean>>({});return <section className="card membrane-exploration"><div className="section-label">PhET · 通膜觀察</div><h2>先觀察，再配對通膜路徑</h2><OperationLayout visual={<><div className="phet-frame"><iframe src={url} title="PhET 細胞膜運輸互動模擬" allowFullScreen/></div><div className="phet-toolbar"><a href={url} target="_blank" rel="noopener noreferrer">模擬無法載入？在新分頁開啟</a></div></>}><div className="controls"><Button variant="outline" disabled={active===0} onClick={()=>setActive(active-1)}>上一任務</Button><strong>{active+1} / {tasks.length}</strong><Button variant="outline" disabled={active===tasks.length-1} onClick={()=>setActive(active+1)}>下一任務</Button></div><div className="membrane-tasks">{tasks.map(([title,instruction,options,answer],i)=>i===active&&<section className="concept-task" key={title}><h3>{title}</h3><StepGuide key={title} steps={instruction.split(/(?<=。)/).filter(Boolean)}/><Pick label="選擇符合觀察的內容" options={[...options]} value={answers[i]||''} onChange={value=>{setAnswers({...answers,[i]:value});setChecked({...checked,[i]:false});}}/><Button variant="outline" disabled={!answers[i]} onClick={()=>setChecked({...checked,[i]:true})}>檢查觀察</Button><p role="status">{checked[i]?(answers[i]===options[answer]?'✓ 正確！'+options[answer]:'再觀察一次：注意物質種類，以及膜上是否有適合的運輸蛋白。'):''}</p></section>)}</div></OperationLayout><p className="insight">關鍵：運輸蛋白具有選擇性。離子常透過專屬通道；葡萄糖通常由專屬載體蛋白協助通過。</p></section>}
