'use client';
import {useState} from 'react';
import {OperationLayout} from './operation-layout';
import {Button} from '@/components/ui/button';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {FlaskConical,RotateCcw,CheckCircle2,ArrowRight} from 'lucide-react';
import {type SimState,concentration,diffusion,osmosis,cellResult} from '@/lib/model';
import {Figure,Cups,Distribution,OsmosisDiagram,CellDiagram} from './diagrams';
export function Pick({label,options,value,onChange}:{label:string;options:string[];value:string;onChange:(v:string)=>void}){return <fieldset className="pick"><legend>{label}</legend><RadioGroup className="pick-options" value={value} onValueChange={v=>onChange(String(v))}>{options.map((o,i)=><label key={o} className={'pick-option '+(value===o?'selected':'')}><RadioGroupItem value={o}/><span>{o}</span></label>)}</RadioGroup></fieldset>}
export function Exploration({page:p,sim:s,onChange}:{page:number;sim:SimState;onChange:(s:SimState)=>void}){const [phase,setPhase]=useState(0);const set=(v:Partial<SimState>)=>onChange({...s,...v});const record=(key:string,result:string,condition:string)=>set({shown:true,observations:{...s.observations,[key]:{condition,prediction:s.prediction,result,reading:p===4?(s.reading===0?'水濃度':'溶質濃度'):undefined,appearance:s.appearance}},readings:p===4?Array.from(new Set([...s.readings,s.reading])):s.readings});const reset=()=>set({shown:false,prediction:'',appearance:'',step:0,paused:true});const seen=(name:string)=>Array.from(new Set([...(s.seen||[]),name]));
const conditions=p===1?['只加水','只加色素','只減水']:p===2?['左側較濃','右側較濃','起初均勻']:p===4?['左側溶質較低','右側溶質較低','兩側相同']:['生理食鹽水','純水','濃食鹽水'];const predicted=p===1?['較濃','較淡','不變']:p===2?['整體較多往左','整體較多往右','無偏向']:p===4?['左往右較多','右往左較多','兩向大致相同']:['進水較多','出水較多','大致相同'];const result=p===1?concentration(s.condition):p===2?diffusion(s.condition):p===4?osmosis(s.condition):cellResult(s.cell||0,s.condition).water;const total=p===5?6:3;const key=p===5?`${s.cell||0}-${s.condition}`:String(s.condition);const advance=()=>{const step=s.step+1;const observation={condition:conditions[s.condition],prediction:s.prediction,result:diffusion(s.condition)+'；最後整體均勻，個別仍隨機移動'};set({step,shown:true,paused:true,observations:step>=2?{...s.observations,[key]:observation}:s.observations});};
return <section className="card exploration"><div className="section-label"><FlaskConical size={19}/>探索實驗 · {p===1?'濃淡條件':p===2?'擴散趨勢':p===4?'只通水的膜':'細胞水量與外觀'}</div><div className="explore-heading"><h2>先預測，再用觀察找證據</h2><span className="pill">{Object.keys(s.observations).length} / {total} 組已觀察</span></div><p className="small">定性模型 · 每次只改一項條件 · 預測不計能力分</p><OperationLayout visual={<Figure title={p===1?'同一杯的前後比較':p===2?'整體分布與個別移動':p===4?'同一方向的兩種讀法':'新的比較：從初始細胞開始'}>{p===1?<Cups condition={s.condition} shown={s.shown}/>:p===2?<><Distribution condition={s.condition} step={s.step}/><div className="legend"><span>金色外框：標記一粒</span><span>逐步觀察，不是真實時間</span></div></>:p===4?<OsmosisDiagram condition={s.condition} shown={s.shown} reading={s.reading}/>:<div className="double"><div><p className="diagram-context">初始細胞</p><CellDiagram plant={s.cell===1}/></div><div><p className="diagram-context">{s.shown?'處置後的示意':'尚未顯示結果'}</p><CellDiagram plant={s.cell===1} pure={s.condition===1} salt={s.condition===2} shown={s.shown}/></div></div>}</Figure>}><div className="current-conditions"><strong>目前條件：{p===5?(['紅血球','植物細胞'][s.cell||0]+' × '):''}{conditions[s.condition]}</strong><p>{p===1?(s.condition===1?'水不變，只增加色素。':'色素不變，只改變水。'):p===4?'只有水可以通過膜，溶質不能通過。':'每次從初始細胞開始比較。'}</p>{p===4&&<div className="controls">{['看水濃度','看溶質濃度'].map((v,i)=><Button key={v} variant={s.reading===i?'default':'outline'} onClick={()=>set({reading:i})}>{v}</Button>)}</div>}</div><div className="controls"><Button variant={phase===0?'default':'outline'} onClick={()=>setPhase(0)}>1 設定條件</Button><Button variant={phase===1?'default':'outline'} onClick={()=>setPhase(1)}>2 預測與觀察</Button></div>{phase===0?<><p className="step-guide">先選擇條件，對照左側操作區，再進入預測。</p>{p===5&&<Pick label="① 選擇細胞種類" options={['紅血球','植物細胞']} value={['紅血球','植物細胞'][s.cell||0]} onChange={v=>set({cell:v==='紅血球'?0:1,shown:false,prediction:'',appearance:''})}/>}
<Pick label={p===5?'② 選擇溶液':'① 選擇起始條件'} options={conditions} value={conditions[s.condition]} onChange={v=>set({condition:conditions.indexOf(v),shown:false,prediction:'',appearance:'',step:0,paused:true})}/>
{p===1&&<div className="fixed-condition">固定條件：{s.condition===1?'水不變，只增加色素。':'色素不變，只改變水。'} 每次從同一基準比較；只減水不是倒出混合液。</div>}
{p===2&&<div className="fixed-condition">固定條件：同種物質、總量不變、兩側等大且連通；虛線不是膜或隔板。</div>}

<Button onClick={()=>setPhase(1)}>設定完成，開始預測</Button></>:<>
<Pick label={p===5?'③ 預測水量關係':'② 我的預測'} options={predicted} value={s.prediction} onChange={v=>set({prediction:v,shown:false,step:0})}/>{p===5&&<Pick label="④ 預測外觀" options={['形狀維持','膨脹，最後可能破裂','略膨脹，不至破裂','萎縮']} value={s.appearance||''} onChange={v=>set({appearance:v,shown:false})}/>}
<div className="controls">{p===2?<><Button disabled={!s.prediction} onClick={advance}><ArrowRight/>{s.step>=2?'再觀察個別移動':'下一個觀察畫面'}</Button><Button variant="outline" onClick={()=>set({paused:true})}>暫停（目前採逐步觀察）</Button><Button variant="outline" disabled={!s.prediction} onClick={()=>{record(key,result+'；最後均勻，個別仍有隨機移動',conditions[s.condition]);onChange({...s,shown:true,step:2,paused:true,observations:{...s.observations,[key]:{condition:conditions[s.condition],prediction:s.prediction,result:result+'；最後均勻，個別仍有隨機移動'}}});}}>靜態三階段</Button></>:<Button disabled={!s.prediction||(p===5&&!s.appearance)} onClick={()=>record(key,p===5?result+'；'+cellResult(s.cell||0,s.condition).shape:result,p===5?['紅血球','植物細胞'][s.cell||0]+' × '+conditions[s.condition]:conditions[s.condition])}><FlaskConical/>顯示{p===4?'水的趨勢':p===5?'水量與外觀':'觀察結果'}</Button>}<Button variant="outline" onClick={reset}><RotateCcw/>重設本次</Button></div>
{!s.prediction&&<p className="small">先留下預測，才會顯示結果。預測可以不正確。</p>}
{s.shown&&<div className="observation-result" role="status"><strong>觀察結果：{p===2?s.step<2?'逐漸散開':result+'；最後均勻':result}</strong><p>{p===1?['水增加，色素保持，相對比例變小。','水保持，色素增加，相對比例變大。','水減少，色素保持，相對比例變大。'][s.condition]:p===2?'整體逐漸均勻；標記粒子仍可往不同方向移動。均勻不等於停止。':p===4?s.condition===2?'兩向水量大致相同，不是沒有水通過。':'水由水濃度較高往較低，也就是由溶質濃度較低往較高。切換讀法不改變箭頭。':cellResult(s.cell||0,s.condition).shape}</p><p>原預測：{s.observations[key]?.prediction||s.prediction}。{s.prediction===result?'與觀察方向相符。':'請對照條件與圖例，保留原預測作比較。'}</p></div>}
{p===2&&s.step>=2&&<div className="triple static-stages">{[0,1,2].map((st)=><div key={st}><p>{['起始','逐漸分散','整體均勻'][st]}</p><Distribution condition={s.condition} step={st} compact/></div>)}</div>}
</>}</OperationLayout>{Object.keys(s.observations).length>0&&<details className="observation-log"><summary><CheckCircle2 size={17}/>我的觀察紀錄（重設不刪除）</summary><div className="table-scroll"><table><thead><tr><th>條件</th><th>原預測</th><th>觀察結果</th></tr></thead><tbody>{Object.values(s.observations).map(o=><tr key={o.condition}><td>{o.condition}</td><td>{o.prediction}{o.appearance&&'；'+o.appearance}</td><td>{o.result}</td></tr>)}</tbody></table></div></details>}
</section>}
