'use client';
import {useEffect,useState,useRef,useCallback} from 'react';
import {flushSync} from 'react-dom';
import {BookOpen,FlaskConical,ClipboardCheck,ChevronLeft,ChevronRight,Map,Check,Atom,Trophy,Flag,Info,RotateCcw,ArrowUpRight,BookmarkCheck,LockKeyhole} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Progress} from '@/components/ui/progress';
import {Dialog,DialogContent,DialogTitle,DialogDescription,DialogClose} from '@/components/ui/dialog';
import lessons from '@/lib/lessons.json';
import {formative,summative,game} from '@/lib/questions';
import {freshState,freshSim,freshRecord,missingTasks,progressPoints,correctRows,firstQuestionPoints,correctedQuestionPoints,migrateState,canVisitPage,restoreAccessiblePage,type AppState,type AnswerRecord} from '@/lib/model';
import {Figure,CellBoundary,RoutesDiagram,OsmosisDiagram,CellDiagram,Distribution,InkSequence,OxygenExample} from './diagrams';
import {Exploration} from './exploration';
import {PhETExploration} from './phet-exploration';
import {QuestionCard} from './question';
import {ConceptBlocks,AtomOrder,ConcentrationCup,MembraneExploration} from './concept-activities';
import {OperationLayout} from './operation-layout';
import {ImportantFigure} from './important-figure';
import {UploadResults} from './upload-results';
const KEY='cell-explorer-learning-v1';
const shortNames=['原子與分子','比較濃淡','擴散作用','通膜路徑','滲透作用','細胞的變化','整合與成果','成果上傳'];
const durations=[4,4,5,5,4,5,8];
const targets=['辨識細胞、分子與觀察面向','比較固定條件下的濃淡','區分隨機移動與擴散趨勢','匹配物質的全部通膜方式','用兩種濃度讀法說明水的方向','用進出水量與細胞壁解釋外觀'];
const summaries=['細胞膜控制物質進出；分子符號是觀察工具。','比較濃淡，要一起看水與色素的相對關係。','隨機移動可以形成整體由濃往淡的擴散趨勢。','辨認物質後，再看它所有適用的通膜方式。','同一水移動趨勢可以用水與溶質兩種濃度描述。','看進出水量，再看細胞種類；細胞壁影響外觀結果。'];
export default function Home(){const[s,setS]=useState<AppState>(freshState);const[ready,setReady]=useState(false);const[resume,setResume]=useState(false);const[mapOpen,setMapOpen]=useState(false);const[navPending,setNavPending]=useState(false);const[ended,setEnded]=useState(false);const[storageError,setStorageError]=useState(false);const ref=useRef(s);ref.current=s;
useEffect(()=>{try{const saved=localStorage.getItem(KEY);if(saved){const parsed=JSON.parse(saved);if(parsed.version===1&&parsed.page>=0&&parsed.page<8&&parsed.answers&&parsed.sims&&parsed.exam&&Array.isArray(parsed.completed)){setS(restoreAccessiblePage(migrateState({...freshState(),...parsed,scoreVersion:parsed.scoreVersion})));setResume(true);}}}catch{setStorageError(true);}setReady(true);},[]);
useEffect(()=>{if(!ready)return;try{localStorage.setItem(KEY,JSON.stringify(s));}catch{setStorageError(true);}},[s,ready]);
useEffect(()=>{if(!ready)return;const fresh:number[]=[];for(let p=0;p<7;p++)if(!s.completed.includes(p)&&missingTasks(s,p).length===0)fresh.push(p);if(fresh.length)setS(prev=>({...prev,completed:[...new Set([...prev.completed,...fresh])]}));},[s,ready]);
useEffect(()=>{if(!ready)return;const save=()=>{const cur=ref.current;const next={...cur,scroll:{...cur.scroll,[cur.page+'-'+cur.tab]:window.scrollY}};try{localStorage.setItem(KEY,JSON.stringify(next));}catch{/* in-memory progress remains available */}};window.addEventListener('pagehide',save);return()=>window.removeEventListener('pagehide',save);},[ready]);
const navigate=useCallback((p:number,tab='read',restore=false)=>{const cur=ref.current;if(!canVisitPage(cur,p)){setNavPending(true);return;}const next={...cur,page:p,tab,scroll:{...cur.scroll,[cur.page+'-'+cur.tab]:window.scrollY},exam:{...cur.exam,reviewed:cur.exam.reviewed||(cur.page===6&&p!==6&&Object.keys(cur.exam.answers).length>0)}};setS(next);setMapOpen(false);setNavPending(false);setEnded(false);requestAnimationFrame(()=>window.scrollTo({top:restore?(next.scroll[p+'-'+tab]||0):0,behavior:'instant'}));},[]);
useEffect(()=>{if(!ready)return;const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,opts:{signal:AbortSignal})=>void|Promise<void>}}).modelContext;if(!context?.registerTool)return;const life=new AbortController();const tools=[{name:'read_learning_progress',title:'讀取目前學習進度',description:'讀取此裝置的七頁學習完成狀態與成果上傳頁與三種獨立分數，不包含題庫答案。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:false},execute:()=>{const a=ref.current;return {page:a.page+1,completed:a.completed.map(p=>p+1),points:progressPoints(a),firstAssessment:a.firstExam??null,bestAssessment:a.bestExam??null,bestGame:a.bestGame??null,pending:'濃食鹽水活動暫未開放'};}},{name:'navigate_learning_page',title:'前往學習頁',description:'導覽到指定的已開放學習頁。這個動作不代表完成活動。',inputSchema:{type:'object',properties:{page:{type:'integer',minimum:1,maximum:8}},required:['page'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:(input:unknown)=>{const page=(input as {page?:number})?.page;if(!Number.isInteger(page)||page!<1||page!>8)throw new Error('page 必須是 1 至 8 的整數');if(!canVisitPage(ref.current,page!-1))throw new Error('請先完成前面的學習頁');flushSync(()=>navigate(page!-1));return {page,title:lessons[page!-1].title};}}];for(const t of tools){try{Promise.resolve(context.registerTool(t,{signal:life.signal})).catch(()=>{});}catch{/* progressive enhancement */}}return()=>life.abort();},[ready,navigate]);
const changeAnswer=(id:string,value:AnswerRecord)=>setS(prev=>({...prev,answers:{...prev.answers,[id]:value}}));
const changeExam=(id:string,value:AnswerRecord)=>setS(prev=>{const answers={...prev.exam.answers,[id]:value};const done=summative.every(q=>answers[q.id]?.submitted);let next={...prev,exam:{...prev.exam,answers}};if(done&&prev.exam.score===undefined){const score=summative.reduce((total,q)=>total+firstQuestionPoints(answers[q.id]),0);next={...next,exam:{...next.exam,score},rounds:[...prev.rounds,{...next.exam,score}],firstExam:prev.firstExam??score,bestExam:Math.max(prev.bestExam??0,score)};}return next;});
const changeGame=(id:string,value:AnswerRecord)=>setS(prev=>{const answers={...prev.game,[id]:value};const done=game.every(q=>answers[q.id]?.score!==undefined);const wasDone=game.every(q=>prev.game[q.id]?.score!==undefined);const score=game.reduce((t,q)=>t+(answers[q.id]?.score||0),0);return {...prev,game:answers,...(done&&!wasDone?{gameRounds:[...prev.gameRounds,score],bestGame:Math.max(prev.bestGame??0,score)}:{})};});
const p=s.page;const sim=s.sims[p]||freshSim();const missing=missingTasks(s,p);const revealed=s.exam.score!==undefined;const tab=(value:unknown)=>{const v=String(value);setS(cur=>({...cur,tab:v,scroll:{...cur.scroll,[p+'-'+cur.tab]:window.scrollY}}));requestAnimationFrame(()=>document.getElementById('lesson-tabs')?.scrollIntoView({block:'start',behavior:'instant'}));};
const review=(page:number)=>navigate(page,'read',true);
const restartDraft=()=>{setResume(false);setS(cur=>{const sims={...cur.sims};const existing=sims[cur.page];if(existing)sims[cur.page]={...freshSim(),observations:existing.observations,seen:existing.seen,readings:existing.readings};const answers={...cur.answers};for(const [id,a]of Object.entries(answers))if(!a.first)answers[id]={...a,draft:[]};const exam={...cur.exam,answers:Object.fromEntries(Object.entries(cur.exam.answers).map(([id,a])=>[id,a.submitted?a:{...a,draft:[]}]))};return {...cur,sims,answers,exam};});};
return <><a className="skip-link" href="#main-content">跳至學習內容</a><header className="topbar"><a className="brand" href="/" onClick={e=>{e.preventDefault();setMapOpen(true);}}><span className="brand-mark"><Atom size={26}/></span><span>細胞探索室<small>CELL EXPLORER</small></span></a><span className="header-unit">國中自然 <i>/</i> 物質進出細胞的方式</span><Button variant="outline" onClick={()=>setMapOpen(true)}><Map size={17}/>課程地圖</Button></header>
<div className="journey-wrap"><nav className="journey" aria-label="學習與成果上傳分頁">{lessons.map((l,i)=><button key={l.title} disabled={!canVisitPage(s,i)} aria-label={`${i+1} ${l.title}，${!canVisitPage(s,i)?'尚未解鎖':i===7?'隨時可上傳':s.completed.includes(i)?'已完成':'尚未完成'}`} aria-current={i===p?'step':undefined} onClick={()=>navigate(i)} className={'journey-step '+(i===p?'active ':'')+(s.completed.includes(i)?'done':'')}><span className="step-circle">{!canVisitPage(s,i)?<LockKeyhole size={15}/>:s.completed.includes(i)?<Check size={17}/>:String(i+1).padStart(2,'0')}</span><span className="step-label">{shortNames[i]}</span></button>)}</nav></div>
<main className="workspace" id="main-content">{storageError&&<div className="pending">此瀏覽器未能保存紀錄，目前可繼續學習；關閉後可能無法恢復。</div>}{resume&&<div className="resume-banner"><BookmarkCheck/><div><strong>歡迎回來，學習紀錄已恢復。</strong><p>停在第 {p+1} 頁。首次答案、已完成項目與答案已保留，積分依新規則計算。</p></div><Button onClick={()=>{setResume(false);requestAnimationFrame(()=>window.scrollTo(0,s.scroll[p+'-'+s.tab]||0));}}>繼續上次</Button><Button variant="ghost" onClick={restartDraft}>重做目前活動</Button></div>}
<div className="lesson-head"><div><div className="eyebrow">CHAPTER {String(p+1).padStart(2,'0')} / 08 <span>·</span> {p===7?'成果上傳':p===6?'整合與自我檢核':'觀察、比較、找證據'}</div><h1>{lessons[p].title}</h1><p className="lead">{p===7?'確認你的學習成果，傳送給老師。':p===0?'從細胞的邊界出發，看見物質移動的祕密。':p===6?'把圖像、條件與原因放在一起，檢查自己的理解。':summaries[p]}</p></div><span className="time-tag">{p===7?'隨時開放上傳':`約 ${durations[p]} 分鐘 · ${s.completed.includes(p)?'已開放任務完成':'依自己的步調學習'}`}</span></div>
{p===7?<UploadResults state={s} onIdentity={student=>setS(cur=>({...cur,student}))} onUnlock={manualUnlocked=>setS(cur=>restoreAccessiblePage({...cur,manualUnlocked}))}/>:p<6?<><Tabs value={s.tab} onValueChange={tab} id="lesson-tabs" className="lesson-tabs"><TabsList><TabsTrigger value="read"><BookOpen/>先讀一讀</TabsTrigger><TabsTrigger value="explore"><FlaskConical/>{p===3?'動手操作':'動手探索'}</TabsTrigger><TabsTrigger value="check"><ClipboardCheck/>檢查理解</TabsTrigger></TabsList>
<TabsContent value={s.tab} className="tab-surface">{s.tab==='read'&&<><div className={'intro-grid '+([2,3,5].includes(p)?'wide-reading':'')}><article className="card reading"><div className="section-label"><BookOpen size={18}/>認識概念</div><h2>{['從原子、分子到細胞與生物','看起來一樣多，就一樣濃嗎？','從一滴紅墨水，到均勻的分布','細胞膜，是有選擇的邊界','追蹤的是水，先說清楚濃度','先看水量，再看細胞的外觀'][p]}</h2><ConceptBlocks texts={lessons[p].paragraphs.slice(0,p===0?5:p===2?3:2)}/><div className="insight">本頁目標：{targets[p]}</div></article><div className="reading-visual">{p===0?<AtomOrder/>:p===1?<ConcentrationCup/>:p===2||p===3||p===5?<ImportantFigure key={p} page={p}/>:<Figure title="水可以通過，溶質不能通過"><OsmosisDiagram shown/></Figure>}</div></div>
<section className="card reading more-reading"><div className="section-label">把關係接起來</div><ConceptBlocks texts={lessons[p].paragraphs.slice(p===0?5:p===2?3:2)}/><div className="reading-bottom"><Button onClick={()=>tab('explore')}>讀完了，開始{p===3?'配對':'探索'}<ChevronRight/></Button></div></section></>}
{s.tab==='explore'&&(p===3?<><MembraneExploration/><div className="insight">先讀完整路徑圖，再替八種物質選出全部方式。水可以複選。此配對同時是本頁評量，不重複計分。</div><Button className="return-reading" variant="outline" onClick={()=>tab('read')}>回看完整圖</Button><OperationLayout visual={<Figure title="物質的全部通膜路徑"><RoutesDiagram/></Figure>}><QuestionCard guided question={{...formative[p],figure:undefined}} record={s.answers[formative[p].id]||freshRecord()} onChange={v=>changeAnswer(formative[p].id,v)} onReview={()=>tab('read')}/></OperationLayout></>:<>{p===0||p===2?<PhETExploration page={p} sim={sim} answers={s.answers} onAnswer={changeAnswer} onChange={v=>setS(cur=>({...cur,sims:{...cur.sims,[p]:v}}))}/>:<Exploration page={p} sim={sim} onChange={v=>setS(cur=>({...cur,sims:{...cur.sims,[p]:v}}))}/>}<div className="section-end"><p>觀察完成後，用一題整理你的理解。</p><Button onClick={()=>tab('check')}>前往檢查理解<ChevronRight/></Button></div></>)}
{s.tab==='check'&&<><div className="assessment-note"><LightbulbIcon/>答錯可以看提示並修正，完成不必全對。首次答案會保留。</div><QuestionCard question={formative[p]} record={s.answers[formative[p].id]||freshRecord()} onChange={v=>changeAnswer(formative[p].id,v)} onReview={()=>tab('read')}/>{p===5&&<div className="pending">你已完成本頁目前開放的題目後，就可以前往下一頁。</div>}</>}
</TabsContent></Tabs></>:<><section className="card exam-intro"><div className="section-label"><ClipboardCheck size={19}/>六題整合評量 · 不限時</div>{lessons[6].paragraphs.slice(0,2).map(t=><p key={t}>{t}</p>)}<div className="exam-status"><span>本輪已提交 {summative.filter(q=>s.exam.answers[q.id]?.submitted).length} / 6 題</span><Progress value={summative.filter(q=>s.exam.answers[q.id]?.submitted).length/6*100} aria-label="本輪評量提交進度"/></div>{s.exam.reviewed&&<span className="pill">本輪有回看學習內容</span>}</section>
{revealed&&<section className="card results" id="results"><div className="section-label"><Flag size={20}/>本輪結果與學習證據</div><h2>用紀錄，找到下一個要複習的概念</h2><div className="result-scores"><div><span>首次評量</span><strong>{s.firstExam}<small> / 12</small></strong></div><div><span>本輪評量</span><strong>{s.exam.score}<small> / 12</small></strong></div><div><span>修正後 · 已看回饋</span><strong>{summative.reduce((t,q)=>t+correctedQuestionPoints(s.exam.answers[q.id]),0)}<small> / 12</small></strong></div></div><p className="small">最高分 {s.bestExam} / 12（可能含重做）。下方可修正後提交；第二次起答對得 1 分，修正不覆蓋首次或最高分。</p><div className="target-list">{targets.map((t,i)=>{const a=s.exam.answers[summative[i].id];return <div key={t}><span className="target-number">O0{i+1}</span><div><strong>{t}</strong><p>本輪首次 {firstQuestionPoints(a)} / 2 · {a?.firstCorrect?.every(Boolean)?'本輪已有支持證據':'待複習'}{i===5?'；濃食鹽水活動暫未開放':''}</p></div><Button variant="outline" onClick={()=>review(i)}>回看<ArrowUpRight/></Button></div>})}</div><div className="pending">濃食鹽水活動待確認。開放內容完成不等於整個單元已掌握。</div><div className="controls"><Button variant="outline" onClick={()=>setS(cur=>({...cur,exam:{answers:{},reviewed:false}}))}><RotateCcw/>再做評量一輪</Button><Button onClick={()=>navigate(7)}>前往 08 成果上傳</Button></div></section>}
{summative.map((q,i)=><QuestionCard key={q.id} question={q} record={s.exam.answers[q.id]||freshRecord()} onChange={v=>changeExam(q.id,v)} exam revealed={revealed} onReview={()=>review(i)}/>)}
{!revealed&&<div className="section-end"><p>尚未作答：{summative.filter(q=>!s.exam.answers[q.id]?.submitted).map(q=>q.id).join('、')||'無'}</p><Button disabled={!summative.every(q=>s.exam.answers[q.id]?.submitted)} onClick={()=>document.getElementById('results')?.scrollIntoView()}>看本輪結果</Button></div>}
<section className="card game-section"><div className="section-label"><Trophy size={19}/>選玩 · 證據配對</div><h2>理由，要能支持同一個結論</h2><p>不限時，三張概念卡，最高 6 分。可跳過；不影響必修進度，也不增加學習進度積分。</p>{!s.gameOpen?<Button onClick={()=>setS(cur=>({...cur,gameOpen:true}))}>選玩：證據配對</Button>:<><Button variant="ghost" onClick={()=>setS(cur=>({...cur,gameOpen:false}))}>收起遊戲（保留本輪）</Button>{game.map(q=><QuestionCard key={q.id} question={q} record={s.game[q.id]||freshRecord()} onChange={v=>changeGame(q.id,v)} onReview={()=>review(q.id==='Q14甲'?3:5)}/>)}{game.every(q=>s.game[q.id]?.score!==undefined)&&<div className="observation-result"><strong>本輪 {game.reduce((t,q)=>t+(s.game[q.id]?.score||0),0)} / 6 · 遊戲最高 {s.bestGame} / 6</strong><p>這三張卡是概念練習；高分不代表已測完整個單元。</p><Button variant="outline" onClick={()=>setS(cur=>({...cur,game:{}}))}>再玩遊戲一輪</Button></div>}</>}</section></>}
<section className="page-navigation">{p<7&&<div><strong>{s.completed.includes(p)?'✓ 本頁已開放任務完成':'本頁任務'}</strong><p>{missing.length?`還有 ${missing.length} 個項目待完成，完成後解鎖下一頁。`:'完成與答對率分開記錄。'}{p===5?' 濃食鹽水活動待確認。':''}</p><details><summary>查看任務清單</summary>{missing.length?<ul>{missing.map(t=><li key={t}>{t}</li>)}</ul>:<p>本頁已開放的必做活動與作答均已完成。</p>}</details></div>}<div className="controls">{p>0&&p<7&&<Button variant="outline" onClick={()=>navigate(p-1)}><ChevronLeft/>上一頁</Button>}{p<6?<Button disabled={!canVisitPage(s,p+1)} onClick={()=>navigate(p+1)}>下一步<ChevronRight/></Button>:p===6?<Button onClick={()=>navigate(7)}>08 成果上傳<ChevronRight/></Button>:<Button variant="outline" onClick={()=>setMapOpen(true)}>回課程地圖</Button>}</div></section>
<footer className="source-footer"><span>細胞探索室 · 七年級自然 2–3</span><span>已開放內容可依自己的步調學習 · 選玩另約 2 分鐘</span><p>學習紀錄保留在此瀏覽器；在成果上傳頁按下上傳後，才會送出班級、座號、姓名與分數。</p></footer>
</main><aside className="scorebar" aria-label="學習紀錄"><div className="scorebar-progress"><div><span>目前開放內容</span><strong>{s.completed.length} / 7 頁</strong></div><Progress value={s.completed.length/7*100} aria-label="目前開放內容完成頁數"/></div><div className="score-item"><span>學習進度積分</span><strong>{progressPoints(s)}<small> / 24</small></strong></div><div className="score-item"><span>評量最高分</span><strong>{s.bestExam===undefined?'尚未完成':s.bestExam+' / 12'}</strong></div><div className="score-item"><span>遊戲最高分</span><strong>{s.bestGame===undefined?'尚未遊玩':s.bestGame+' / 6'}</strong></div><span className="score-note">三種分數分開記錄<br/>首次答對 2 分；重答對 1 分<br/>完成頁面不另加分</span></aside>
<Dialog open={mapOpen} onOpenChange={setMapOpen}><DialogContent className="map-dialog" showCloseButton={false}><DialogTitle>你的學習路線</DialogTitle><DialogDescription>完成前面的學習頁後，下一頁會自動解鎖；已解鎖的頁面可回看。第 08 頁始終開放。</DialogDescription><div className="map-list">{lessons.map((l,i)=><button key={l.title} disabled={!canVisitPage(s,i)} onClick={()=>navigate(i)} className={i===p?'current':''}><span className="map-number">{!canVisitPage(s,i)?<LockKeyhole size={18}/>:s.completed.includes(i)?'✓':String(i+1).padStart(2,'0')}</span><span><strong>{l.title}</strong><small>{i===7?'隨時可上傳成果':!canVisitPage(s,i)?'請先完成前面的學習頁':s.completed.includes(i)?'已開放任務完成':missingTasks(s,i).length+' 項待完成'}{i===5?' · 高濃度暫未開放':''}</small></span><ChevronRight size={19}/></button>)}</div><p className="small">7 / 7 表示已開放任務完成；濃食鹽水活動與 Q07 暫未開放。</p><DialogClose render={<Button variant="outline"/>}>關閉課程地圖</DialogClose></DialogContent></Dialog>
<Dialog open={navPending} onOpenChange={setNavPending}><DialogContent className="navigation-dialog" showCloseButton={false}><DialogTitle>還有幾個觀察值得完成</DialogTitle><DialogDescription>請先完成前面的學習頁，再前往下一頁。完成不需要全部答對；成果上傳頁始終開放。</DialogDescription><ul className="missing-list">{missing.map(t=><li key={t}>{t}</li>)}</ul><Button onClick={()=>setNavPending(false)}>繼續本頁</Button><Button variant="outline" onClick={()=>navigate(7)}>前往 08 成果上傳</Button></DialogContent></Dialog>
<Dialog open={ended} onOpenChange={setEnded}><DialogContent className="navigation-dialog" showCloseButton={false}><DialogTitle>本次學習紀錄已保留</DialogTitle><DialogDescription>你已完成本輪六題作答。可依目標紀錄回看待複習的概念。</DialogDescription><p>目前開放內容：{s.completed.length} / 7 頁<br/>首次評量：{s.firstExam??'尚未完成'} / 12</p><p className="pending">濃食鹽水活動暫未開放，不代表你答錯。</p><DialogClose render={<Button/>}>回到成果</DialogClose></DialogContent></Dialog></>;
}
function LightbulbIcon(){return <Info size={19}/>}
