'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {RadioGroup,RadioGroupItem} from '@/components/ui/radio-group';
import {Checkbox} from '@/components/ui/checkbox';
import {CheckCircle2,Lightbulb,RotateCcw} from 'lucide-react';
import {correctRows,allAnswered,submitRecord,type AnswerRecord} from '@/lib/model';
import type {Question,Row} from '@/lib/questions';
import {QuizFigure} from './diagrams';
export function Choices({row,value,onChange,disabled=false,id}:{row:Row;value:number[];onChange:(v:number[])=>void;disabled?:boolean;id:string}){const option=(text:string,i:number)=><label key={i} className={'option '+(value.includes(i)?'selected':'')} htmlFor={id+'-'+i}>{row.multi?<Checkbox id={id+'-'+i} checked={value.includes(i)} disabled={disabled} onCheckedChange={checked=>onChange(checked?[...value,i]:value.filter(v=>v!==i))}/>:<RadioGroupItem id={id+'-'+i} value={String(i)} disabled={disabled}/>}<span><b className="option-letter">{String.fromCharCode(65+i)}</b>{text}</span>{value.includes(i)&&<span className="selected-check">✓</span>}</label>;return row.multi?<div className="choices" role="group" aria-label={row.text}>{row.options.map(option)}</div>:<RadioGroup value={value[0]===undefined?null:String(value[0])} onValueChange={v=>onChange([Number(v)])} aria-label={row.text}>{row.options.map(option)}</RadioGroup>}
export function QuestionCard({question:q,record:a,onChange,exam=false,revealed=false,onReview}:{question:Question;record:AnswerRecord;onChange:(v:AnswerRecord)=>void;exam?:boolean;revealed?:boolean;onReview?:()=>void}){const [error,setError]=useState('');const correctness=correctRows(q.rows,a.draft);const locked=exam?!revealed&&!!a.submitted:a.score!==undefined;const full=!!a.demonstrated||revealed;const submit=()=>{if(!allAnswered(q.rows,a.draft)){setError('請先完成第 '+q.rows.map((_,i)=>(a.draft[i]?.length?null:i+1)).filter(Boolean).join('、')+' 列，再提交。');return;}setError('');onChange(exam&&revealed?{...submitRecord(q.rows,{...a,submitted:false},true),correctionCorrect:correctRows(q.rows,a.draft).every(Boolean)}:submitRecord(q.rows,a,exam));};return <article className="question-card" id={q.id}><div className="question-heading"><span className="question-id">{q.id}</span><h3>{q.title}</h3>{a.score!==undefined&&<span className="pill success"><CheckCircle2 size={15}/>已結算 {a.score} 分</span>}{exam&&a.submitted&&!revealed&&<span className="pill">已提交 · 本輪結束後看回饋</span>}</div>{q.intro&&<p>{q.intro}</p>}{q.figure&&<QuizFigure kind={q.figure}/>}<p className="small">每題首次答對 2 分，第二次起答對 1 分；看解析完成不給答對積分。</p><div className="question-rows">{q.rows.map((row,i)=><div className={'question-row '+((a.feedback||revealed)&&a.submitted?(correctness[i]?'correct':'incorrect'):'')} key={i}><p className="row-label">{q.rows.length>1&&<span>{i+1}.</span>} {row.text}{row.multi&&<small>（可複選）</small>}</p><Choices row={row} value={a.draft[i]||[]} id={q.id+'r'+i} disabled={locked} onChange={v=>{const draft=[...a.draft];draft[i]=v;onChange({...a,draft,submitted:exam&&!revealed?a.submitted:false,correctionCorrect:revealed?false:a.correctionCorrect});setError('');}}/>{((a.feedback&&a.submitted)||revealed)&&<p className={'row-feedback '+(correctness[i]?'good':'bad')}>{correctness[i]?'✓ 這一列正確。':'↻ 這一列需要再想一想。'}{(full||correctness[i])&&' '+row.feedback}</p>}</div>)}</div>{error&&<p className="error" role="alert">{error}</p>}
<div className="controls">{!locked&&<Button onClick={submit}>{revealed?'提交修正答案':a.first?'重新作答並檢查':exam?'提交這題':'檢查我的答案'}</Button>}{!exam&&a.score===undefined&&<Button variant="outline" onClick={()=>onChange({...a,hint:true})}><Lightbulb/>看提示</Button>}{!exam&&a.first&&a.score===undefined&&<Button variant="ghost" onClick={()=>onChange({...a,hint:true,demonstrated:true,feedback:true,score:0})}>看完整解析並完成</Button>}{onReview&&(!exam||revealed)&&<Button variant="ghost" onClick={onReview}>回看對應圖文 ↗</Button>}</div>
{!exam&&(a.hint||(a.first&&a.score===undefined))&&<div className="hint" role="status"><Lightbulb size={19}/><p>{q.hint} {a.first&&a.score===undefined&&'目前待修正；你可以重選原錯列，或看完整解析完成。'}</p></div>}
{!exam&&a.demonstrated&&<div className="explanation"><h4>完整解析 · 示範後完成</h4>{q.rows.map((r,i)=><p key={i}>{q.rows.length>1?`${i+1}. `:''}{r.answer.map(x=>r.options[x]).join('、')}。{r.feedback}</p>)}</div>}
{!exam&&a.score!==undefined&&q.rescue&&<details className="rescue"><summary><RotateCcw size={16}/>示範後再練一次（不另加分）</summary>{q.rescue.map((r,i)=><div className="question-row" key={i}><p className="row-label">{r.text}</p><Choices row={r} value={a.rescueDraft?.[i]||[]} id={q.id+'rescue'+i} onChange={v=>{const draft=[...(a.rescueDraft||[])];draft[i]=v;onChange({...a,rescueDraft:draft,rescueSubmitted:false});}}/>{a.rescueSubmitted&&<p className={correctRows(q.rescue!,a.rescueDraft||[])[i]?'good':'bad'}>{correctRows(q.rescue!,a.rescueDraft||[])[i]?'✓ 正確':'再想想：'+r.feedback}</p>}</div>)}<Button variant="outline" disabled={!allAnswered(q.rescue,a.rescueDraft||[])} onClick={()=>onChange({...a,rescueSubmitted:true})}>檢查再練答案</Button></details>}
{a.first&&(!exam||revealed)&&<details className="first-record"><summary>第一次答案與修正紀錄</summary><p>首次：{a.firstCorrect?.map((v,i)=>`${i+1}. ${v?'正確':'待複習'}`).join(' ／ ')}{a.firstHint?'（提交前已使用提示）':''}</p><p>第一次選擇：{a.first.map((v,i)=>v.map(k=>q.rows[i]?.options[k]).join('＋')).join(' ／ ')}</p><p>目前：{correctness.map((v,i)=>`${i+1}. ${v?'正確':'待複習'}`).join(' ／ ')}{a.demonstrated?'（已看完整示範）':a.hint?'（已看提示）':''}</p></details>}</article>}
